# Generated by Django 3.0.7 on 2020-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='label',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
