# Generated by Django 3.0.7 on 2020-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0010_primer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
