# Generated by Django 3.0.7 on 2020-08-13 17:21

import cardonalab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0019_library_libstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='libstock',
            name='forward_primer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardonalab.Primer'),
        ),
        migrations.AddField(
            model_name='libstock',
            name='gene_target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='libstock',
            name='letter',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libstock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libstock',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libstock',
            name='plasmid_map',
            field=models.FileField(null=True, upload_to=cardonalab.models._plasmidmap_upload_location),
        ),
        migrations.AddField(
            model_name='libstock',
            name='plate',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libstock',
            name='resistance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='libstock',
            name='species',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
