# Generated by Django 4.0.6 on 2022-07-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0025_plasmid_primers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBulkDataLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxNo', models.CharField(max_length=256)),
                ('locusTag', models.CharField(max_length=256)),
                ('downStreamGene', models.CharField(max_length=256)),
                ('forwardPrimer', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
                ('resistance', models.CharField(max_length=256)),
                ('essential', models.BooleanField(default=False)),
                ('growthDefense', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
