# Generated by Django 4.0.6 on 2022-07-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0026_librarybulkdataload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybulkdataload',
            name='date_created',
        ),
    ]
