# Generated by Django 4.0.6 on 2022-07-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0027_remove_librarybulkdataload_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='boxNo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='downStreamGene',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='forwardPrimer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='locusTag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='resistance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='librarybulkdataload',
            name='species',
            field=models.CharField(max_length=255),
        ),
    ]
