# Generated by Django 4.0.6 on 2022-07-31 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0029_alter_librarybulkdataload_essential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybulkdataload',
            name='plate',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarybulkdataload',
            name='wellLetter',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarybulkdataload',
            name='wellNo',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
