# Generated by Django 4.0.6 on 2022-09-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0030_librarybulkdataload_plate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryBulkDataLoad',
            new_name='CrispriLibrary',
        ),
        migrations.RenameField(
            model_name='crisprilibrary',
            old_name='growthDefense',
            new_name='growthDefect',
        ),
    ]
