# Generated by Django 3.0.7 on 2020-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0003_auto_20200612_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='number',
            field=models.IntegerField(editable=False),
        ),
    ]
