# Generated by Django 3.0.7 on 2020-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0008_chemical_msds'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
    ]
