# Generated by Django 3.0.7 on 2020-08-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0021_auto_20200813_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
    ]
