# Generated by Django 3.0.7 on 2020-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0022_auto_20200814_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': ' Libraries'},
        ),
        migrations.AlterField(
            model_name='libstock',
            name='stock_id',
            field=models.CharField(max_length=255),
        ),
    ]
