# Generated by Django 3.0.7 on 2020-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0024_auto_20200820_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmid',
            name='primers',
            field=models.ManyToManyField(blank=True, to='cardonalab.Primer'),
        ),
    ]
