# Generated by Django 3.0.7 on 2020-06-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0006_auto_20200612_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage_Location',
            new_name='StorageLocation',
        ),
    ]
