# Generated by Django 3.0.7 on 2020-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0007_auto_20200612_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='msds',
            field=models.URLField(blank=True, verbose_name='Link to MSDS'),
        ),
    ]
