# Generated by Django 3.0.7 on 2020-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardonalab', '0016_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cardonalab.Tag'),
        ),
    ]
