# Generated by Django 3.0.7 on 2020-07-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardonalab', '0017_auto_20200706_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'verbose_name_plural': '        Chemicals'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': '       Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='plasmid',
            options={'verbose_name_plural': '    Plasmids'},
        ),
        migrations.AlterModelOptions(
            name='primer',
            options={'verbose_name_plural': '     Primers'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'verbose_name_plural': ' Protocols'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': '  Stocks'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name_plural': '      Storage Locations'},
        ),
        migrations.AlterModelOptions(
            name='strain',
            options={'verbose_name_plural': '   Strains'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
